[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "pybatsim"
version = "4.0.0-beta.0"
description = "Python API and schedulers for Batsim"
readme = "README.rst"
keywords = [
  "scheduler",
  "simulation",
]
authors = [
  { name = "Henri Casanova", email = "henric@hawaii.edu" },
  { name = "Pierre-François Dutot", email = "pfdutot@imag.fr" },
  { name = "David Glesser", email = "david.glesser@imag.fr" },
  { name = "Steffen Lackner", email = "lackner@cs.tu-darmstadt.de" },
  { name = "Michael Mercier", email = "michael.mercier@inria.fr" },
  { name = "Clément Mommessin", email = "clement.mommessin@inria.fr" },
  { name = "Millian Poquet", email = "millian.poquet@inria.fr" },
  { name = "Olivier Richard", email = "olivier.richard@imag.fr" },
]
maintainers = [
  { name = "Raphaël Bleuse", email = "raphael.bleuse@inria.fr" },
]
license = "LGPL-3.0-only"
requires-python = "~= 3.10"

dynamic = [
  # managed by poetry
  "classifiers",  # inject python requirements and license classifiers
  "dependencies",
]

[project.urls]
homepage = "https://gitlab.inria.fr/batsim/pybatsim"
repository = "https://gitlab.inria.fr/batsim/pybatsim.git"
issues = "https://gitlab.inria.fr/batsim/pybatsim/-/issues"

[project.scripts]
pybatsim = "pybatsim.cmdline:main"

# definition of officially maintained schedulers
[project.entry-points."pybatsim.schedulers"]
random = "pybatsim.schedulers.random:RandomScheduler"
prototype = "pybatsim.schedulers.prototypeEDC:PrototypeEDC"

[tool.poetry]
classifiers = [
  "Development Status :: 4 - Beta",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering",
  "Topic :: System :: Distributed Computing",
]
packages = [
  {include = "pybatsim", from = "src"},
]

[tool.poetry.dependencies]
procset = "^1.0"
sortedcontainers = "^2.4.0"
pyzmq = ">=26.0.0"

[tool.poetry.group.dev.dependencies]
coverage = "^6.2"
Sphinx = "^4.3.1"
ruff = "^0.11.2"
black = "^25.1.0"

[tool.ruff]
extend-exclude = [
  "_legacy",
]

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
extend-select = [
  "YTT",
  "BLE",
  "FBT",
  "B",
  "A",
  "C4",
  "EM",
  "EXE",
  "FIX",
  "RET",
  "SLF",
  "SIM",
  "TID",
  "ARG",
  "I",
  "N",
  "PERF",
  "E",
  "W",
  "PL",
  "UP",
  "TRY",
]
